### PR TITLE
Add Iron Man movie

### PR DESCRIPTION
**Pull request by viciouskitten**

### CODE REVIEW

**Comment by haxzie-xx** [comment]
Hey @viciouskitten You sure the movie "Shaun of the dead" has anything related to tech?

**Comment by viciouskitten** [comment]
Hey, I thought it was for "Geeks" too. Happy to change it if you don't agree though :)

**Comment by viciouskitten** [comment]
@haxzie I will change it to Iron Man - pretty techy :)

**Comment by haxzie-xx** [comment]
Thanks @viciouskitten :tada:

**Review by haxzie-xx — APPROVED** [review]

**Pull request merged**
